### PR TITLE
Export interfaces validator (validateJsonLogic)

### LINKED ISSUE #44: validateJsonLogic not exported
Hi. I need validateJsonLogic in my code because I decode a bunch of rules from a big JSON structure. And I want to check them when they are already `interface{}`.

Please export it

### PR DESCRIPTION
**Pull request by Evgenus**
`validateJsonLogic` -> `ValidateJsonLogic`

fixes #44

### CODE REVIEW

**Comment by Evgenus** [comment]
@diegoholiveira, please review

**Comment by Evgenus** [comment]
Can we make a version release, please?

**Comment by diegoholiveira** [comment]
> Can we make a version release, please?

Like this one?

https://github.com/diegoholiveira/jsonlogic/releases/tag/v3.1.0

**Comment by Evgenus** [comment]
> > Can we make a version release, please?
> 
> Like this one?
> 
> https://github.com/diegoholiveira/jsonlogic/releases/tag/v3.1.0

Yes, thanks you

**Pull request merged**
